/*! Copyright © 2015, 2020, Oracle and/or its affiliates. All rights reserved. */
/*! mmpackage v1.21 */
/*! jQuery | Copyright JS Foundation and other contributors, https://js.foundation */
/*v1.21.0.1*/
'use strict';(function(){function Z(w,V,W){Z=void 0;(new Function("scriptName","applier",w))(V,W)}var w=window.console||{log:function(){},error:function(){}};(function(){function U(a,e,g){var l=[],y;for(y in a)a.hasOwnProperty(y)&&(g?l=l.concat(e(a[y])):l.push(e(a[y])));return l}function V(a,e){var g=[],l;for(l in a)a.hasOwnProperty(l)&&e(a[l])&&g.push(a[l]);return g}function W(a,e){var g=void 0,l;for(l in a)if(a.hasOwnProperty(l)&&!0===e(a[l])){g=a[l];break}return g}function aa(a,e){if(F(e))return!!W(a,e);for(var g=
a.length;g--;)if(a[g]===e)return!0;return!1}function K(a,e,g){g=g||0;for(var l=a.length;g<l;g++)if(a[g]===e||F(e)&&e(a[g]))return g;return-1}function F(a){return"function"===typeof a}function Q(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)}function J(a){return"string"===typeof a}function H(a){return"undefined"===typeof a}function X(a){return"number"===typeof a}function T(a){if(null===a||"object"!==typeof a)return a;var e=a.constructor(),g;for(g in a)a.hasOwnProperty(g)&&
(e[g]=T(a[g]));return e}function R(a,e){a=H(a)?{}:a;e=H(e)?{}:e;if(null===e||"object"!==typeof e)return e;var g={},l;if("object"===typeof a)for(l in a)a.hasOwnProperty(l)&&(g[l]=a[l]);for(l in e)e.hasOwnProperty(l)&&(g[l]?Q(g[l])&&Q(e[l])?g[l]=g[l].concat(e[l]):g[l]=R(g[l],e[l]):g[l]=e[l]);return g}function E(a){return H(a)||null===a?!0:1>a.replace(/\s/g,"").length}function da(a){return"mm_style"+(a?"_"+a:"")+("_"+ea++)}function G(a){return a.replace(/^\s+|\s+$/gm,"")}function B(){var a=arguments,
e={},g=1;J(a[1])||(e=a[1],g=2);for(var l=a[0],a=Q(a[2])?a[2]:D(a,g),g=0;g<a.length;g++)e[a[g]]=function(a){return function(){return a.apply(e,arguments)}}(l[a[g]]);return e}function Y(){function a(a){var e,l="";for(e=0;e<a;e++)l+=(16*Math.random()%16|0).toString(16);return l}return a(8)+"-"+a(4)+"-4"+a(3)+"-"+a(4)+"-"+a(12)}function O(a,e){for(var g in a)a.hasOwnProperty(g)&&e(a[g],g)}function fa(a){return function(){try{a()}catch(e){w.log(e.message||e)}}}function ba(a){var e=a.getAttribute("href"),
g=a.getAttribute("target");return{hrefHasJS:/(^| )javascript:/i.test(e),sameSite:a.hostname===window.location.hostname,notRequiresReload:/^#|(^| )javascript: ?void/i.test(e)||!a.hasAttribute("href"),target:g}}function ca(a){for(;a&&"a"!==a.tagName.toLowerCase();)a=a.parentElement;return a}function D(a,e,g){g=H(g)?a.length:g;e=e||0;if(Q(a))return Array.prototype.slice.call(a,e,g);var l=[],y=(g||0)-e;if(0<y)for(l=Array(y),g=0;g<y;g++)l[g]=a[e+g];return l}function ga(){return function(){}}function I(a){a=
a||{};var e="";H(a.opacity)||(a.filter="alpha(opacity="+100*a.opacity+")");O(a,function(a,l){e+=l+": "+a+" !important; "});return G(e)}function ha(a,e,g){function l(c){if(!v[c]){var f=e[c],b={};try{f(b,y.requireClass,y.require),b.exports=y.options.isDlpEnabled?b.dlp||b.exports:b.basic||b.exports}catch(C){w.log("ERROR: "+C.message+" in module "+c)}h[c]&&(b.exports=b.exports.extend(h[c]));v[c]=b}return v[c]}var y=this,v,d;y.options=g||{};var h=y.options.moduleExtensions||{};this.reset=function(c){v=
{};d=c||{}};y.reset(a);this.require=function(c,f){l(c);var b=v[c];return b&&b.config&&b.config.singleton?(d[c]||(d[c]=new b.exports(y.options)),d[c]):new b.exports(f)};this.requireClass=function(c){l(c);return v[c].exports};this.addModule=function(c,f){e[c]=f}}var ia=Z,ea=1,ka={CGApi:function(a,e,g){a.config={singleton:!0};a.exports=function(){function a(c,f,b,d){var a=h.getParam("uv",d)||{};c=G(c);a[c]=a[c]||[];if(void 0===f)f=1;else if(""===f||isNaN(f))f=0,b="NaN";a[c].push(f+(b?","+encodeURIComponent(b):
""));h.setParam("uv",a,d)}function e(c,f,b,d){var a=h.getParam("uat",b)||{};a[G(c)]=G(f+"");h.setParam("uat",a,b,d)}function v(c,f){var b=h.getParam("rul",f)||[];c=U(c,function(b){return encodeURIComponent(H(b)?"":b)}).join(",")+";";b.push(c);h.setParam("rul",b,f)}function d(c,f,b,d){var a=h.getParam("ids",b)||{};a[c+""]=f+"";h.setParam("ids",a,b,d)}var h=g("Engine");this.setAction=function(c,f,b){a(c,f,b,h.storeStrategy.request)};this.postAction=function(c,f,b){a(c,f,b,h.storeStrategy.deferredRequest)};
this.setAttr=function(c,f){e(c,f,h.storeStrategy.request)};this.storeAttr=function(c,f,b){e(c,f,h.storeStrategy.persistent,b)};this.getAttr=function(c){return(h.getParam("uat",h.storeStrategy.persistent)||{})[G(c)]};this.removeAttr=function(c){var f=h.getParam("uat",h.storeStrategy.persistent)||{};delete f[G(c)];h.setParam("uat",f,h.storeStrategy.persistent,365)};this.setId=function(c,f){d(c,f,h.storeStrategy.request)};this.storeId=function(c,f,b){d(c,f,h.storeStrategy.persistent,b)};this.removeId=
function(c){var f=h.getParam("ids",h.storeStrategy.persistent)||{};delete f[c+""];h.setParam("ids",f,h.storeStrategy.persistent,365)};this.hasActions=function(){var c=h.getParam("uv",h.storeStrategy.request)||{},f=h.getParam("uv",h.storeStrategy.deferredRequest)||{};return c&&"{}"!==JSON.stringify(c)||f&&"{}"!==JSON.stringify(f)};this.request=function(c,f){h.setParam("pageid",c.pageId,h.storeStrategy.request);c.pagePrefix&&h.setParam("pp",c.pagePrefix,h.storeStrategy.request);h.CGRequest(f)};this.setData=
function(c,f,b){h.setData(c,f,b)};this.getData=function(c){return h.getData(c)};this.clearData=function(c){h.clearData(c)};this.getServerAttrs=function(){return h.getServerAttrs()};this.setCategoryFilter=function(c,f,b){v({categoryId:c,categoryName:f,including:b?1:0},h.storeStrategy.request)};this.setProductFilter=function(c,f,b){v({categoryId:c,productId:f,including:b?1:0,isProduct:1},h.storeStrategy.request)};this.setProduct=function(c){h.setParam("mrp",c,h.storeStrategy.request)}}},Class:function(a,
e,g){e=function(){};e.extend=function(a){var l=function(){l.superclass.constructor.apply(this,arguments);var d={};O(this,function(h,c){d[c]=h});this.base=d;return a.apply(this,arguments)},e=function(){};e.prototype=this.prototype;l.prototype=new e;l.prototype.constructor=l;l.superclass=this.prototype;l.implementation=a;l.extend=this.extend;l.inherit=this.inherit;return l};e.inherit=function(a){(a.implementation||a).call(this.prototype)};a.exports=e},Cookies:function(a,e,g){a.config={singleton:!0};
a.exports=function(a){var l=this,e=a.cookieDomain,d=a.isBaseStorageSecure,h=encodeURIComponent,c=decodeURIComponent;this.set=function(c,b,a){if(!c||!J(c))return w.error("You can't use cookies.set without specifying cookie name."),this;a=a||{};H(a.secure)&&!H(d)&&(a.secure=d,H(a.sameSite)&&d&&(a.sameSite="none"));var f=";domain="+(a.domain||e),p=";path="+(a.path||"/");if(a.expires){var n=a.expires;var r=new Date;r.setTime(r.getTime()+864E5*n);n=";expires="+r.toGMTString()}else n="";r=a.secure?";secure":
"";a=a.sameSite?";sameSite="+a.sameSite:"";document.cookie=h(c)+"="+h(b)+f+p+n+r+a;return this};this.remove=function(c,b){if(!c||!J(c))return w.error("You can't use cookies.remove without specifying cookie name."),this;b||(b={});b.expires=-1;var f=this.get(c);H(f)||this.set(c,"",b);return this};this.get=function(f){if(!f||!J(f))return w.error("You can't use cookies.get without specifying cookie name."),this;f=new RegExp("(?:^|; )"+h(f).replace(/([.$?*|{}()\[\]\\\/+^])/g,"\\$1")+"((;|$)|(=([^;]*)))");
return(f=document.cookie.match(f))?c(f[4]||""):void 0};this.getWrapper=function(){return B(l,"get","set","remove")}}},Events:function(a,e,g){a.config={singleton:!1};e=e("Class").extend(function(){function a(c,f){c=c.split(".");if(1===c.length)var b=c[0];else if(2===c.length){b=c[0];if(0===b.length||-1!==b.indexOf("*"))return!1;b=c[1]}else return!1;if(!b.length)return!1;if(-1!==b.indexOf("*"))if(f){if("*"!==b)return!1}else return!1;return c}function e(c,f,b,a){h[c]={event_data:f,callback:!0===a?b:
void 0};if(d[c]){c=d[c];for(a=0;a<c.length;a++)c[a].call(v,f);F(b)&&b()}}var v=this,d={},h={};this.on=function(c,f,b){if(!J(c))return w.log("eventName is incorrect"),this;if(!a(c,!0))return w.error("'"+c+"' is incorrect for On"),this;if(b&&(b=h[c])){try{f.apply({},[b.event_data])}catch(C){}b.callback&&b.callback()}d[c]=d[c]||[];d[c].push(f);return this};this.off=function(c,f){if(!J(c))return w.log("eventName is incorrect"),this;d[c]=d[c]||[];for(var b=d[c].length;b--;)f==d[c][b]&&d[c].splice(b,1);
return this};this.trigger=function(c,f,b,d){if(!J(c))return w.log("eventName is incorrect"),this;var h=a(c,!1);if(!h)return w.error("'"+c+"' is incorrect for Trigger"),this;e(c,f,b,d);2==h.length&&e(h[0]+".*",f,b,d);return this};this.getWrapper=function(){return B(v,{},"on","off","trigger")}});a.exports=e},EventsSite:function(a,e,g){a.config={singleton:!1};var l=e("Events").extend(function(){var a=this;this.domReady=function(){var a=!1,d=[],h=function(){document.addEventListener?(document.removeEventListener("DOMContentLoaded",
c,!1),window.removeEventListener("load",c,!1)):(document.detachEvent("onreadystatechange",c),window.detachEvent("onload",c))},c=function(){if(document.addEventListener||"load"===event.type||"complete"===document.readyState)h(),f()},f=function(){if(!a){if(!document.body)return setTimeout(f);a=!0;for(var c=0;c<d.length;c++)try{(0,d[c])()}catch(z){w.log(z)}}};if("complete"===document.readyState)f();else if(document.addEventListener)document.addEventListener("DOMContentLoaded",c,!1),window.addEventListener("load",
c,!1);else{document.attachEvent("onreadystatechange",c);window.attachEvent("onload",c);var b=!1;try{b=null==window.frameElement&&document.documentElement}catch(C){}b&&b.doScroll&&function z(){if(!a){try{b.doScroll("left")}catch(p){return setTimeout(z,50)}h();f()}}()}return function(c){c=c||function(){};if(a){try{c()}catch(z){w.log(z)}return!0}d.push(c);return!1}}();this.getWrapper=function(){return B(a,a.base.getWrapper(),"domReady")}});e=e("Events").extend(function(){var a=this,l=g("Dlp");this.domReady=
function(a){return l.parentReady(a)};this.getWrapper=function(){return B(a,a.base.getWrapper(),"domReady")}});a.basic=l;a.dlp=e},EventsCampaign:function(a,e,g){a.config={singleton:!1};e=e("EventsSite").extend(function(){var a=this,e=g("Events");this.variantJsExecuted=function(a){e.on("variantJsExecuted",function(d){a(d.elementName,d.variantName)},!0);return this};this.contentSeen=function(a){e.on("sendContentSeen",function(){a()},!0);return this};this.triggerVariantJsExecuted=function(a){e.trigger("variantJsExecuted",
a);return this};this.triggerContentSeen=function(){e.trigger("sendContentSeen");return this};this.getWrapper=function(){return B(a,a.base.getWrapper(),"variantJsExecuted","contentSeen")}});a.exports=e},Deferred:function(a,e,g){function l(a,d){a=a||{};for(var h in d)d.hasOwnProperty(h)&&(a[h]="object"===typeof d[h]?l(a[h],d[h]):d[h]);return a}function y(a){for(var d=[["resolve","done",[],"resolved"],["reject","fail",[],"rejected"],["notify","progress",[]]],h="pending",c={state:function(){return h},
always:function(){f.done(arguments).fail(arguments);return this},then:function(){var b=arguments;return y(function(a){for(var n=0;n<d.length;n++)(function(b,n){f[d[b][1]](function(){var k=F(n[b])&&n[b].apply(this,arguments);if(k&&F(k.promise))k.promise().done(a.resolve).fail(a.reject).progress(a.notify);else a[d[b][0]+"With"](this===c?a.promise():this,n[b]?[k]:arguments)})})(n,b);b=null}).promise()},promise:function(b){return null!=b?l(b,c):c}},f={},b,e,g=0;g<d.length;g++)(function(a){var n=d[a],
r=n[2];c[n[1]]=function(){for(var a=0;a<arguments.length;a++)(function(a){F(a)?h===n[3]?a.apply(b,e):r.push(a):a&&a.length&&"string"!==typeof a&&c[n[1]].apply(this,a)})(arguments[a]);return this};f[n[0]]=function(){f[n[0]+"With"](this===f?c:this,arguments);return this};f[n[0]+"With"]=function(c,a){if("pending"==h)for(b=c,e=a,n[3]&&(h=n[3]);r.length;)r.shift().apply(c,a);return this}})(g);c.promise(f);a&&a.call(f,f);return f}a.exports=y},When:function(a,e,g){var l=e("Deferred");a.exports=function(){var a=
0,e=F(arguments[0]),d=e?[l()]:arguments,h=Array.prototype.slice.call(d),c=h.length,f=1!==c||d[0]&&F(d[0].promise)?c:0,b=1===f?d[0]:l(),g=function(c,a,d){return function(k){a[c]=this;d[c]=1<arguments.length?Array.prototype.slice.call(arguments):k;d===n?b.notifyWith(a,d):--f||b.resolveWith(a,d)}},z;if(e){d=arguments;var p=setInterval(function(){d[0]()?b.resolve():d[1]&&F(d[1])&&d[1]()&&b.reject()},50);b.always(function(){clearInterval(p)})}else if(1<c){var n=Array(c);e=Array(c);for(z=Array(c);a<c;a++)h[a]&&
F(h[a].promise)?h[a].promise().done(g(a,z,h)).fail(b.reject).progress(g(a,e,n)):--f}f||b.resolveWith(z,h);return b.promise()}},Renderer:function(a,e,g){a.config={singleton:!1};var l=0,y=0,v=e("Class").extend(function(a){function c(){m&&(clearTimeout(m),m=null);X(k)&&(m=setTimeout(function(){b.showAll()},k))}function f(c){if(c=(c?(c.Name||c)+"":"").toLowerCase()){var q=a.getElement(c)||{},b=q.Data;if(b)for(var k="",f="",d=0;d<b.length;d++)"Css"===b[d].Type?k=b[d].Data:"Html"===b[d].Type&&""!==G(b[d].Data)?
f=b[d].Data:"Script"===b[d].Type&&(n.runElementScript(a,c,{html:f,css:k},b[d].Data),a.events.triggerVariantJsExecuted({elementName:q.Name?q.Name:"",variantName:q.VariantName?q.VariantName:""}),f=k="")}else w.log("renderElement should receive element or elementName")}var b=this,d=e("When"),h=e("Deferred"),p=g("CGApi"),n=g("Engine"),r=g("Dom"),u={},L=y++,k=7E3,m;this.hide=function(b,q){if(!b)return w.log("You can't use renderer.hide without params"),this;-1===b.indexOf("{")&&(b+="{position:relative;left:-10000px;top:-10000px;}");
q=(q||"gen_"+l++)+"_"+L;u[q]=!0;r.addCss(b,q);c();return this};this.show=function(b){if(!b)return w.log("You can't use renderer.show without params"),this;var q=b+"_"+L;if(!u[q])return w.log("ID ("+b+") you try to show is not found"),this;delete u[q];r.removeCss(q);return this};this.showAll=function(){var b=[];O(u,function(q,c){b.push(c)});r.removeMultiCss(b);u={};m&&(clearTimeout(m),m=null);return this};this.unhideAfter=function(b){"never"===b||X(b)&&0<=b?(k=b,c()):w.log('You can use renderer.unhideAfter with number greater 0 or "never" string only.');
return this};this.getContent=function(b){var q=h();b={pageId:b||(a.getPagePrefix()?"":a.getName()),pagePrefix:a.getPagePrefix()};p.request(b,function(b){b?q.resolve():q.reject()});return q.promise()};this.runVariantJs=function(b){if(0<arguments.length)f(b);else for(var q=a.getElements(),c=0;c<q.length;c++)f(q[c]);return this};this.waitUntilDom=function(b){return d(b,n.events.domReady)};this.when=function(){return d.apply(b,arguments)}}),d=v.extend(function(a){var c=e("When"),d=g("Engine");this.waitForElement=
function(b){return c(function(){return null!=document.querySelector(b)},d.events.domReady)}}),v=v.extend(function(a){var c=e("When"),d=e("Deferred"),b=g("Engine"),h=g("Dlp");this.waitForElement=function(a){var f=new d,n=!1,r=function(b){n=b};c(function(){h.checkNodeExist(a).done(r);return n},b.events.domReady).done(function(){f.resolve()}).fail(function(){h.checkNodeExist(a).done(r).then(function(b){b?f.resolve():f.reject()},function(){f.reject()})});return f.promise()}});a.dlp=v;a.basic=d},Campaign:function(a,
e,g){var l=e("Element");a.exports=function(a){function e(b){return function(c){return c.Name===b}}var d=this,h=g("Site"),c=g("Action"),f=a.Name,b=a.PagePrefix,C=g("BaseStorage",{namespace:f}),z={},p=U(a.Elements,function(b){return new l(b)}),n=a.Recommendations,r=!1;this.sendContentSeen=function(){r||(c.send(a.CSName),d.events.triggerContentSeen(),r=!0)};this.updateData=function(b){for(var c=0;c<b.Elements.length;c++){var a=K(p,e(b.Elements[c].Name));0<=a?p[a]=new l(b.Elements[c]):p.push(new l(b.Elements[c]))}n=
b.Recommendations};this.getElements=function(){return p};this.getRecommendations=function(){return n};this.getExperience=function(){var b=h.getPageExperiences()[f],c={},a;for(a in b)b.hasOwnProperty(a)&&(c[a]=b[a]);return c};this.getElement=function(b){b||w.log("You can't use campaign.getElement without params");b=b.toLowerCase();return W(p,e(b))||null};this.getStyles=function(b){return U(p,function(c){return c.getStyles(b)},!0)};this.isDefault=function(){if(!p||0==p.length)throw Error("There is no content for campaign "+
f+".");for(var b=!0,c=0;c<p.length;c++)b=b&&"Default"===p[c].VariantName;return b};this.getName=function(){return f};this.getPagePrefix=function(){return b};this.setData=function(b,c,a){C.set(b,c,a)};this.getData=function(b){return C.get(b)};this.clearData=function(b){C.set(b,null,-1)};this.events=g("EventsCampaign");this.getContext=function(){var b={};b.scope=z;b.isDefault=function(){return d.isDefault()};b.getElements=function(){for(var b={},c=0;c<p.length;c++)b[p[c].Name]=p[c].clone();return b};
b.getElement=function(b){return(b=d.getElement(b))?b.clone():b};b.getRecommendations=function(){return U(n,T)};b.getStyles=function(b){return d.getStyles(b)};b.getExperience=function(){return d.getExperience()};b.getName=function(){return d.getName()};b.getPagePrefix=function(){return d.getPagePrefix()};b.events=d.events;b.setData=function(b,c,a){return d.setData(b,c,a)};b.getData=function(b){return d.getData(b)};b.clearData=function(b){return d.clearData(b)};b.sendContentSeen=function(){d.getElements()&&
d.getElements().length&&d.sendContentSeen()};return b}}},Element:function(a,e,g){function l(a){var e=this;e.Name=a.Name;e.HTMLId=a.HTMLId;e.Order=a.Order;e.VariantName=a.VariantName;e.Data=T(a.Data);this.getStyles=function(a){return U(V(e.Data,function(d){return"Css"===d.Type&&(H(a)||d.Attrs.id===a)}),function(a){return a.Data})};this.clone=function(){return new l(e)}}a.exports=l},Site:function(a,e,g){a.config={singleton:!0};a.exports=function(){var a=this,e={},g={};this.getPageExperiences=function(){var a,
h,c={};for(a in g)if(g.hasOwnProperty(a))for(h in c[a]={},g[a])g[a].hasOwnProperty(h)&&(c[a][h]=g[a][h]);return c};this.setPageExperiences=function(a){var d;for(d in a)if(a.hasOwnProperty(d)){var c=a[d];var f=g[d];"undefined"===typeof f&&(g[d]={},f=g[d]);for(var b in c)c.hasOwnProperty(b)&&(f[b]=c[b])}return g};this.getContext=function(){var d={};d.scope=e;d.getPageExperiences=a.getPageExperiences;return d}}},Style:function(a,e,g){a.config={singleton:!0};e=e("Class").extend(function(){function a(){var c=
d.createElement("style");c.type="text/css";c.media="screen";c.id=g.htmlId;var b=d.getElementsByTagName("head")[0];b.insertBefore(c,b.lastChild);return c}function e(){var a="";O(c,function(b){a+=b});return a}var g=this,d=document;g.htmlId=da("mm_cdApiStyleId");var h=a(),c={};this.set=function(c){(h=d.getElementById(g.htmlId))||(h=a());h.styleSheet?h.styleSheet.cssText=c:h.innerHTML=c};this.add=function(a,b){if(b){if(c[b]){w.error("Style with specified ID("+b+") already exists");return}c[b]=a}else c.nr=
c.nr||"",c.nr+=a;g.set(e())};this.remove=function(){O(D(arguments),function(a){"nr"!==a&&c[a]?delete c[a]:w.error("Could not remove non-existent style "+a+".")});g.set(e())};this.clear=function(){c={};g.set(e())}});a.exports=e},Action:function(a,e,g){a.config={singleton:!0};var l=e("Class").extend(function(){var a=this,l=g("CGApi"),d=e("Deferred");this.sendActions=function(d,c,f){for(var b=!0,h,e,l,n,r=0;r<d.length;r++)n=d[r].name,l=d[r].value,e=d[r].attribute,b&=h=d[r].postponedAction,h?a.postpone(n,
l,e):a.set(n,l,e);!b||c?a.send().then(f):F(f)&&f()};this.send=function(a,c,f){var b=d();if(0<arguments.length&&a&&J(a))l.setAction(a,c,f);else if(0!==arguments.length){w.log("You can't use action.send without setting action name");return}l.hasActions()?l.request({pageId:"mmevents"},function(a){a?b.resolve():b.reject()}):b.resolve();return b.promise()};this.postpone=function(a,c,d){if(!a||!J(a))return w.log("You can't use action.postpone without setting action name."),this;l.postAction(a,c,d);return this};
this.set=function(a,c,d){if(!a||!J(a))return w.log("You can't use action.set without setting action name."),this;l.setAction(a,c,d);return this};this.trackClicks=function(d,c,f){g("Dom").trackClicks(d,c,f,a.sendActions)};this.getWrapper=function(){return B(a,"send","postpone","set","trackClicks")}});a.exports=l},Visitor:function(a,e,g){a.config={singleton:!0};var l=e("Class").extend(function(){var a=this,d=e("Deferred"),h=g("CGApi");this.setAttr=function(a,d){h.setAttr(a,d);return this};this.storeAttr=
function(a,d){h.storeAttr(a,d,365);return this};this.getAttr=function(a){return h.getAttr(a)};this.removeAttr=function(a){h.removeAttr(a);return this};this.setId=function(a,d){h.setId(a,d);return this};this.storeId=function(a,d){h.storeId(a,d,365);return this};this.removeId=function(a){h.removeId(a);return this};this.setData=function(a,d,b){h.setData(a,d,b);return this};this.getData=function(a){return h.getData(a)};this.clearData=function(a){return h.clearData(a)};this.requestPage=function(a){var c=
d();h.request({pageId:a},function(b){b?c.resolve():c.reject()});return c.promise()};this.getServerAttrs=function(){return T(h.getServerAttrs())};this.getWrapper=function(){return B(a,"setAttr","storeAttr","getAttr","removeAttr","setId","storeId","removeId","setData","getData","clearData","requestPage","getServerAttrs")}}),y=l.extend(function(){var a=this;this.navigateTo=function(a){!J(a)||E(a)?w.log("CD API Visitor Module: You should pass targetUrl as a non-empty String to visitor.navigateTo()."):
(F(window.stop)?window.stop():document.execCommand("Stop"),window.location.replace(a))};this.getWrapper=function(){return B(a,a.base.getWrapper(),"navigateTo")}}),l=l.extend(function(){var a=this,d=g("Dlp");this.navigateTo=function(a){!J(a)||E(a)?w.log("CD API Visitor Module: You should pass targetUrl as a non-empty String to visitor.navigateTo()."):d.navigateTo(a)};this.getWrapper=function(){return B(a,a.base.getWrapper(),"navigateTo")}});a.basic=y;a.dlp=l},QuerySelector:function(a,e,g){a.config=
{singleton:!0};e=e("Class").extend(function(){function a(a,d){for(var b,e=[],n,r=[],h,l,k=/(\s*([+~>])\s*)?(.*?)\:(has|contains|eq)\((\"|\')?(.+?)\5\)|(\s*([+~>])\s*)?(.+)/g;null!==(n=k.exec(a));)n&&-1<n.index&&(b=n[2]||n[8]||"",h=n[3]||n[9]||"",l=n[4]||"",n=n[6]||"",r.push({splitter:G(b),selector:G(h),queryFunction:G(l),value:G(n)}));for(h=0;h<r.length&&(a=r[h],e=c.findChildren(e,a,d),0!==a.queryFunction.length&&(b=f[a.queryFunction.toLowerCase()],e=b(e,a)),0!==e.length);h++);return e}function e(a,
c){return(a.matches||a.matchesSelector||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector).call(a,c)}function v(a){return a&&">"===a?"direct":a&&"+"===a?"next":"querySelector"}function d(a,c,d){var b=[];a=a.querySelectorAll(d);for(d=0;d<a.length;d++)h.useZindex(a[d])&&b.push(a[d]);return c=c.concat(D(b))}var h=g("Vcb"),c=this;this.find=function(b,c){var d=[],f=Object.prototype.toString.call(b);if("[object Array]"===f||"[object NodeList]"===f||"[object HTMLCollection]"===f)return D(b);
if(!J(b))return[b];b=b.split(",");for(f=0;f<b.length;f++)d=d.concat(a(G(b[f]),c));return d};var f={eq:function(a,c){return 0<a.length&&a[c.value]?[a[c.value]]:[]},contains:function(a,c){for(var b=D(a),d=b.length-1;0<=d;d--)a=b[d].textContent||b[d].innerText,-1===a.indexOf(c.value)&&b.splice(d,1);return b},has:function(a,d){a=D(a);for(var b=a.length-1;0<=b;b--)0===c.find(d.value,a[b]).length&&a.splice(b,1);return a}};this.findChildren=function(a,c,f){var b=[];if(""===c.selector)return a;if(a.length)for(f=
0;f<=a.length-f;f++){var n=a[f],r,h=[];var l=c.selector;for(r=v(c.splitter);"querySelector"!==r;){var k=l.match(/([^ >]+)( \d+)?\s*([>+]?)\s*(.*)/);l=k[4];h.push({selector:k[2]?k[1]+k[2]:k[1],findingType:r});r=v(k[3])}l&&h.push({selector:l,findingType:r});k=h;r=Q(n)?n:[n];for(n=0;n<k.length;n++)if("querySelector"===k[n].findingType){l=k[n].selector;for(var h=[],m=0;m<r.length;m++)h=d(r[m],h,l);r=h}else if("direct"===k[n].findingType){l=k[n].selector;h=[];for(m=0;m<r.length;m++)for(var g=r[m].children,
q=0;g&&q<g.length;q++)1===g[q].nodeType&&e(g[q],l)&&h.push(g[q]);r=h}else if("next"===k[n].findingType)a:{l=r;h=k[n].selector;for(m=0;m<l.length;m++){for(r=l[m].nextSibling;r&&1!==r.nodeType;)r=r.nextSibling;if(r&&e(r,h)){r=[r];break a}}r=[]}k=D(r);b=b.concat(D(k))}else k=d(f||document,[],c.selector),b=D(k);return b};this.isNodeBelongsSelector=function(a,d,f){a=c.find(a,f);for(f=0;f<a.length;f++)if(a[f].isEqualNode(d))return!0;return!1}});a.exports=e},Dom:function(a,e,g){a.config={singleton:!0};var l=
e("Class").extend(function(){function a(a,b,c){return function(){var q=p.find(b[0]);if(q.length)return b[0]=q,a.apply(f,b),c(),!0}}function d(){u=setInterval(function(){for(var a=0;a<r.length;a++)r[a]()&&(r.splice(a,1),--a);r.length||clearInterval(u)},200);l.registerLoop(u)}function h(a,b){if(b&&!l.isVcbActive){var q=z.autoHide(a);return function(){z.removeCss(q)}}return ga()}function c(a,b){return function(){for(var q=b&&[],c=D(arguments),d=p.find(c[0]),k=0;k<d.length;k++)if(d[k]&&d[k].tagName){c[0]=
d[k];var N=a.apply(f,c);b&&q.push(N)}return q}}var f=this,b=e("Deferred"),l=g("Vcb"),z=g("DomPlain"),p=g("QuerySelector"),n=[],r=[],u,L="hide resize freeMove changeStyle guidedMove remove bringToFront changeLinkUrl insertImageBannerBelow insertImageBannerAbove insertImageBannerWithin changeImageBanner editHtml insertHtmlAbove insertHtmlBelow insertHtmlWithin makeLink".split(" "),k=["addCss","removeCss","find"],m=["addListener","removeListener","getNodesAttribute","setNodesAttribute"];this.loop=function(b,
c){return function(){var q=arguments[0],k=D(arguments),N=p.find(q);N.length?(k[0]=N,b.apply(f,k)):J(q)&&(q=h(q,!c),r.length||d(),r.push(a(b,k,q)))}};(function(a,b,d){b=b||{};O(d,function(q){b[q]=f.loop(c(a[q]))})})(z,f,L);B(z,f,k);this.addListener=function(a,b,c){a=p.find(a);for(var q=0;q<a.length;q++){var d=z.addEvent(a[q],b,c);n.push({handler:c,handlerWrapper:d})}};this.removeListener=function(a,b,c){a=p.find(a);for(var q=0;q<a.length;q++)for(var d=0;d<n.length;d++)n[d].handler===c&&z.removeEvent(a[q],
b,n[d].handlerWrapper)};this.trackClicks=f.loop(c(z.trackClicks),!0);this.removeMultiCss=z.removeMultiCss;this.getNodesAttribute=function(){var a=D(arguments);a[0]=p.find(a[0]);var d=new b;d.resolve(c(z.getNodesAttribute,!0).apply(z,a));return d.promise()};var y=f.loop(c(z.setNodesAttribute));this.setNodesAttribute=function(a,b,d,k){var q=D(arguments);"wait"===k?y.apply(f,q):(q[0]=p.find(q[0]),c(z.setNodesAttribute).apply(z,q))};this.getWrapper=function(){var a=B(f,{},m);B(f,a,L);B(z,a,k);return a}}),
y=e("Class").extend(function(){var a=this,d=g("Dlp"),h="addCss removeCss hide resize freeMove changeStyle guidedMove remove bringToFront changeLinkUrl insertImageBannerBelow insertImageBannerAbove insertImageBannerWithin changeImageBanner editHtml setNodesAttribute insertHtmlAbove insertHtmlBelow insertHtmlWithin".split(" "),c=["getNodesAttribute"],f=["addListener","removeListener"];this.addListener=function(a,c,f){d.addListener(a,c,f)};this.removeListener=function(a,c,f){d.removeListener(a,c,f)};
O(h,function(b){a[b]=d.proxy("Dom",b)});O(c,function(b){a[b]=d.proxy("Dom",b,!0)});this.trackClicks=function(a,c,f,h){d.trackClicks(a,c,f,h)};this.removeMultiCss=d.proxy("Dom","removeMultiCss");this.getWrapper=function(){var b=B(a,{},h);B(a,b,c);B(a,b,f);return b}});a.basic=l;a.dlp=y},DomPlain:function(a,e,g){a.config={singleton:!0};e=e("Class").extend(function(){function a(a,b){return window.getComputedStyle?window.getComputedStyle(a,null)[b]:a.currentStyle?a.currentStyle[b]:a.style[b]}function e(a){return a.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,
"").replace(/<title\b[^<]*(?:(?!<\/title>)<[^<]*)*<\/title>/gi,"").replace(/<link\b[^<]*>/gi,"").replace(/<meta\b[^<]*>/gi,"")}function v(a,c){var d=(a.style.cssText.replace(/[^;]$/,"$0;")+c).split(";");c={};for(var f=0;f<d.length;f++)if(d[f]){var k=d[f].split(":");c[k[0].replace(/\s/g,"")]=k[2]?k[1]+":"+k[2]:k[1]}var d="",n;for(n in c)c.hasOwnProperty(n)&&(d+=n+":"+c[n]+"; ");b.setCssText(a,d.replace(/\s$/,""))}function d(b,c,d){var f=a(b,"position");c=c?parseInt(c,10):0;d=d?parseInt(d,10):0;if("relative"===
f||"absolute"===f||"fixed"===f){var k=a(b,"left"),n=a(b,"right");"auto"===k&&"auto"!==n?c="right: "+(parseInt(n,10)-c)+"px !important; ":("auto"===k?k=c:"relative"===a(b,"position")?k=parseInt(k,10)+c:(k=parseInt(b.offsetLeft,10)+c,c=a(b,"margin-left"),"auto"!==c&&(k-=parseInt(c,10))),c="left: "+k+"px !important; ");k=a(b,"top");n=a(b,"bottom");"auto"===k&&"auto"!==n?d="bottom: "+(parseInt(n,10)-d)+"px !important; ":("auto"===k?k=d:"relative"===a(b,"position")?k=parseInt(k,10)+d:(k=parseInt(b.offsetTop,
10)+d,d=a(b,"margin-top"),"auto"!==d&&(k-=parseInt(d,10))),d="top: "+k+"px !important; ")}else f="relative",c="left: "+c+"px !important; ",d="top: "+d+"px !important; ";v(b,c+d+("position: "+f+" !important;"))}function h(a,c){H(c.imageUrl)||"img"!==a.tagName.toLowerCase()||(a.style.visibility="hidden",a.src=c.imageUrl,b.addEvent(a,"load",function(){a.style.visibility=""}));H(c.imageAlt)||a.setAttribute("alt",e(c.imageAlt));H(c.imageTitle)||a.setAttribute("title",e(c.imageTitle))}function c(a){var b=
document.createElement("img");h(b,a);if(void 0!==a.linkUrl){var c=document.createElement("a");c.setAttribute("href",a.linkUrl);c.appendChild(b)}return c||b}function f(a,b){var c=ca(b);b=void 0;if(c){var d=ba(c);if(!(d.sameSite||d.target&&"_blank"===d.target)){a.originalPreventDefault=a.originalPreventDefault||a.preventDefault;a.preventedByClientsCode=a.preventedByClientsCode||a.defaultPrevented&&!a.preventedByCdApiCode;a.preventDefault=function(){a.preventedByClientsCode=!0;a.originalPreventDefault()};
a.originalPreventDefault();a.preventedByCdApiCode=!0;var k=!1;b=function(){var b=c.getAttribute("href");k||a.preventedByClientsCode||(d.hrefHasJS?(new Function(b)).call(window):d.target?window.open(b?c.href:window.location.href,d.target):d.notRequiresReload||window.location.assign(c.href),k=!0)};window.setTimeout(b,2E3)}}return b}var b=this,C=g("Vcb"),z=g("Style"),p=g("QuerySelector");this.setCssText=function(a,b){a.style.cssText=b};this.addCss=function(a,b){if(!Q(a)&&!J(a))return w.log("You try call dom.addCss with wrong arguments."),
this;0===a.length&&w.log("WARNING: You add empty css.");a.join&&(a=a.join("\n"));z.add(a,b);return this};this.removeCss=function(a){if(!a)return w.log("You can't use dom.removeCss without params"),this;z.remove(a);return this};this.removeMultiCss=function(a){z.remove.apply(z,a);return this};this.getStyle=a;this.find=p.find;this.updateElementStyle=v;this.addEvent=function(a,b,c){var d=function(b){b=b||window.event;!b.target&&b.srcElement&&(b.target=b.srcElement);return c.call(a,b)};a.addEventListener?
a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,d);return d};this.removeEvent=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c):a.detachEvent&&a.detachEvent("on"+b,c)};this.addClass=function(a,b){b=G(b);var c=G(a.getAttribute("class")||"");~c.indexOf(b)||a.setAttribute("class",G(c?c+" "+b:b))};this.hide=function(a){v(a,"visibility: hidden !important;")};this.show=function(a){v(a,"visibility: visible !important;")};this.resize=function(a,b,c,f,k){b=parseInt(b,10);c=parseInt(c,
10);v(a,"width: "+b+"px !important; height: "+c+"px !important;");(f||k)&&d(a,f,k)};this.freeMove=d;this.changeStyle=v;this.guidedMove=function(a,b){if(0<=b){var c=a.parentElement;c.removeChild(a);var d=c.children;b<d.length?c.insertBefore(a,d[b]):c.appendChild(a)}};this.remove=function(a){var b=a.parentElement;b&&b.removeChild(a)};this.bringToFront=function(b,c){if("undefined"===typeof c){for(var d=0,f=document.querySelectorAll("*"),k=f.length,e=0;e<k;e++)if(c=parseInt(a(f[e],"z-index"),10),!isNaN(c)&&
d<c&&C.useZindex(f[e])&&(d=c),C.isVcbActive&&d>=C.maxZindex){d=C.maxZindex-11;break}c=d+10}d=a(b,"position");v(b,"z-index: "+c+" !important; position: "+("static"===d||"auto"===d?"relative":d)+" !important;")};this.changeLinkUrl=function(a,c){b.setNodesAttribute(a,"href",c)};this.insertImageBannerAbove=function(a,b){b=c(b);a.parentElement.insertBefore(b,a)};this.insertImageBannerBelow=function(a,b){b=c(b);a.parentElement.insertBefore(b,a.nextSibling)};this.insertImageBannerWithin=function(a,b){b=
c(b);a.appendChild(b)};this.changeImageBanner=function(a,b){if("a"===a.tagName.toLowerCase()){void 0!==b.linkUrl&&a.setAttribute("href",b.linkUrl);a=a.children;for(var c=0;c<a.length;c++)"img"===a[c].tagName.toLowerCase()&&h(a[c],b)}else"img"===a.tagName.toLowerCase()&&(h(a,b),void 0!==b.linkUrl&&"a"===a.parentElement.tagName.toLowerCase()&&a.parentElement.setAttribute("href",b.linkUrl))};this.editHtml=function(a,b){a.innerHTML=e(b)};this.makeLink=function(a,b,c){if("a"===a.tagName.toLowerCase())var d=
a;else d=document.createElement("a"),a.parentElement.insertBefore(d,a),d.appendChild(a);d.setAttribute("href",b);H(c)||d.setAttribute("target",c)};this.setNodesAttribute=function(a,b,c){a.setAttribute(b,c)};this.getNodesAttribute=function(a,b){return a.getAttribute(b)};this.insertHtmlAbove=function(a,b){var c=document.createElement("div");a.parentElement.insertBefore(c,a);c.outerHTML=e(b)};this.insertHtmlBelow=function(a,b){var c=document.createElement("div");a.parentElement.insertBefore(c,a.nextSibling);
c.outerHTML=e(b)};this.insertHtmlWithin=function(a,b){var c=document.createElement("div");a.appendChild(c);c.outerHTML=e(b)};this.autoHide=function(a){a=a.replace(/:eq\(\d*\)/gmi,"");var c=Y();b.addCss(a+"{visibility: hidden;}",c);return c};this.trackClick=function(a,b,c,d){C.isVcbActive?C.registerClickAction(a,b,c):(a["data-mm-events-ref"]||(a["data-mm-events-ref"]={lockFuncs:[]},d(function(b,c){for(var d=a["data-mm-events-ref"].lockFuncs,q=[],k=0;k<d.length;k++){var e=d[k]();if(e){var h=e[0];var l=
h;var g=b;l=g.target===a?!1:J(g.data)&&aa(g.data.split(","),l);l||(q.push({name:h,value:e[1],attribute:e[2],postponedAction:H(e[3])?!0:e[3]}),e=b.data&&J(b.data)?b.data.split(","):[],aa(e,h)||(e.push(h),b.data=e.join()))}}if(q.length){k=ca(a);d=!1;if(k){if(k=ba(k),!k.sameSite||k.notRequiresReload||k.target)d=!0}else k=a.nodeName.toLowerCase(),h=a.getAttribute("type"),("input"===k||"button"===k)&&h&&"submit"===h.toLowerCase()||(d=!0);c(q,d,f(b,a))}})),a["data-mm-events-ref"].lockFuncs.push(function(){return[b.name,
b.value,b.attribute,b.postponedAction]}))};this.trackClicks=function(a,c,d,f){b.trackClick(a,c,d,function(c){b.addEvent(a,"click",function(a){c(a,f)})})};this.removeTrackClicks=function(a,b){if(a&&a["data-mm-events-ref"]){a=a["data-mm-events-ref"].lockFuncs;for(var c=a.length-1;0<=c;c--){var d=a[c]();if(d[0]===b.name&&d[1]===b.value&&d[2]===b.attribute)return a.splice(c,1),!0}}return!1};this.hasTrackClicks=function(a,b){if(a&&a["data-mm-events-ref"]){a=a["data-mm-events-ref"].lockFuncs;for(var c=
a.length-1;0<=c;c--){var d=a[c]();if(d[0]===b.name&&d[1]===b.value&&d[2]===b.attribute)return!0}}return!1}});a.exports=e},Spa:function(a,e,g){a.config={singleton:!0};var l=e("Class").extend(function(){function a(a,q){return function(){var k=arguments[0],f=b.find(k),N={};if(0===f.length||0===m.length)return!1;for(var e=f.length-1;0<=e;e--){var h=D(arguments);h[0]=f[e];if(!1===c.isChanged(q,a,h,A)){var ja=c.makeRollbackObject(f[e],m,q,h,k);N.result=a.apply(d,h);N.operation=a;N.mutationIndex=A;c.registerRollback(ja,
N)}}return!0}}function l(a){var b=null,c=null;this.modificationApply=function(){m=D(a);F(b)&&C.checkConditions(a)?b.apply(null):F(c)&&c();m=[]};this.then=function(a){if(F(a))b=a;else return w.error("You can't use without setting function"),!1;d.forceMutation();return this}.bind(this);this.rollback=function(a){if(F(a))c=a;else return w.error("You can't use without setting function"),!1;return!0}.bind(this)}var d=this,h=g("DomPlain"),c=g("SpaRollback"),f=g("Action"),b=g("QuerySelector"),C=g("Conditions"),
z=g("Watcher"),p=e("Deferred"),n=["when","forceMutation"],r=["element","location"],u="hide resize freeMove changeStyle guidedMove remove bringToFront changeLinkUrl insertImageBannerBelow insertImageBannerAbove insertImageBannerWithin changeImageBanner editHtml insertHtmlAbove insertHtmlBelow insertHtmlWithin makeLink setNodesAttribute getNodesAttribute find".split(" "),L=["trackClicks"],k=[],m=[],A=0,q=!1;this.find=b.find;this.element=C.element;this.location=C.location;this.getNodesAttribute=function(){for(var a=
D(arguments,1),c=b.find(arguments[0]),q=new p,d=[],k=0;k<=c.length-1;k++)d.push(h.getNodesAttribute.bind(h,c[k]).apply(h,a));q.resolve(d);return q.promise()};this.forceMutation=function(){A++;c.runRollbackAll();O(k,function(a){a.modificationApply()})};this.forceRollback=function(){k=[];c.runRollbackAll(!0)};this.when=function(){q||(z.watchNode(document,function(){d.forceMutation()}),q=!0);var a=D(arguments);a=Q(a[0])?a[0]:a;var b=new l(a);0<a.length&&k.push(b);return b};this.getWrapper=function(){var a=
{};B(d,a,n);a.dom={};a.actions={};a.conditions={};B(d,a.dom,u);B(d,a.actions,L);B(d,a.conditions,r);return a};B(h,d,["find"]);(function(b,c,q){c=c||{};O(q,function(q){c[q]=a(b[q],q)})})(h,d,"hide resize freeMove changeStyle guidedMove remove bringToFront changeLinkUrl insertImageBannerBelow insertImageBannerAbove insertImageBannerWithin changeImageBanner editHtml insertHtmlAbove insertHtmlBelow insertHtmlWithin makeLink setNodesAttribute".split(" "));this.spaTrackClick=function(a,b,c,q){h.trackClick(a,
b,c,function(b){h.addEvent(a,"mousedown",function(){a["data-mm-events-mouseup-h"]&&h.removeEvent(a,"mouseup",a["data-mm-events-mouseup-h"]);a["data-mm-events-mouseup-h"]=h.addEvent(a,"mouseup",function(c){b(c,q);h.removeEvent(a,"mouseup",a["data-mm-events-mouseup-h"])})})})};this.spaTrackClicks=a(d.spaTrackClick,"trackClicks");this.trackClicks=function(a,b,c){d.spaTrackClicks(a,b,c,f.sendActions)}});a.exports=l},Conditions:function(a,e,g){a.config={singleton:!0};e=e("Class").extend(function(){function a(a){a=
Q(a[0])?a[0]:a;for(var d=0;d<a.length;d++)"string"===typeof a[d]&&(a[d]=a[d].replace(v,"\\$&").replace(/\*/g,".*"),a[d]=new RegExp("^"+a[d]+"$","i"));return a}var e=g("QuerySelector"),v=/[\\/\^\$\+\?\.\(\)\:\=\!\<\>\|\{\}\,\;\[\]\&\%]/g;this.checkConditions=function(a){return a.every(function(a){return a()})};this.element=function(a){var d=function(){return 0<e.find(a).length};d.not=function(){return function(){return!d()}};return d};this.location=function(d){var e=a(D(arguments)),c=function(){for(var a=
window.location.href.toLowerCase(),b=0;b<e.length;b++)if(e[b].test(a))return!0;return!1};c.not=function(){var d=a(D(arguments));return function(){var a=window.location.href.toLowerCase(),f=c();if(0>=d.length)return!f;for(var e=0;e<d.length;e++)if(d[e].test(a))return!1;return f}};return c}});a.exports=e},SpaRollback:function(a,e,g){a.config={singleton:!0};e=e("Class").extend(function(){function a(a){return"body"===a.nodeName.toLowerCase()||document.body.contains(a)}function e(a,b){if(!a)return!0;var c=
document.createElement("img");c.src=a;return b.getAttribute("src")===c.getAttribute("src")}function v(a,b){a="img"===a.nodeName.toLowerCase()?[a]:a.querySelectorAll("img");for(var c=!1,d=0;d<a.length;d++)c=c||e(b.imageUrl,a[d])&&a[d].alt===(b.imageAlt||"")&&a[d].title===(b.imageTitle||"");return c}function d(b,c,d,k){return b.method===d&&b.parent.isEqualNode(c)&&u.isEqualToolArguments(k,b.args)&&a(b.node)}function h(b,c,d,k){return b.method===d&&a(b.node)&&b.node.isEqualNode(c)&&u.isEqualToolArguments(k,
b.args)}function c(a,b){return u.applyChangeToNode(a.options.operation,a.originNode.cloneNode(!0),a.originParent.cloneNode(!0),b)}function f(a){return-1<K(a,"nodeBelow")||-1<K(a,"nodeAbove")||-1<K(a,"nodeWithin")}function b(a){return-1<K(a,"imageBannerBelow")||-1<K(a,"imageBannerAbove")||-1<K(a,"imageBannerWithin")}function C(a){var b=document.createElement("div");b.innerHTML=a;return 0<b.children.length}function z(a,b,k,f,e,h){for(a=0;a<=m.length-1;a++)if(d(m[a],f,e,h)&&-1<c(m[a],h).parent.innerHTML.indexOf(h[1]))return!0;
return!1}function p(b,c,d,k,f){a(b)&&a(b.parentNode)&&b.parentNode.removeChild(C(f[1])?b.nextElementSibling:b.nextSibling)}function n(b,c,d,k,f){a(b)&&a(b.parentNode)&&b.parentNode.removeChild(C(f[1])?b.previousElementSibling:b.previousSibling)}function r(b,c,d){a(b)&&a(b.parentNode)&&(b.innerHTML=d.innerHTML)}var u=this,L=g("QuerySelector"),k=g("Conditions"),m=[],A={hide:["style"],resize:["style"],freeMove:["style"],changeStyle:["style"],guidedMove:["move"],remove:["remove"],bringToFront:["style"],
changeLinkUrl:["changeLinkUrl"],insertImageBannerBelow:["imageBannerBelow"],insertImageBannerAbove:["imageBannerAbove"],insertImageBannerWithin:["imageBannerWithin"],changeImageBanner:["changeImageBanner"],editHtml:["html"],insertHtmlAbove:["nodeAbove"],insertHtmlBelow:["nodeBelow"],insertHtmlWithin:["nodeWithin"],makeLink:["link"],setNodesAttribute:["attribute"],trackClicks:["trackClicks"]};this.rollbackAttributes=function(a,b,c){for(var d=0;d<c.length;d++)null===b.getAttribute(c[d])?a.removeAttribute(c[d]):
a.setAttribute(c[d],b.getAttribute(c[d]))};this.rollbackHandlers={style:function(a,b,c){a.style.cssText=c.style.cssText},html:function(a,b,c){a.innerHTML=c.innerHTML},attribute:function(a,b,c,d,k){b=a.attributes.length>=c.attributes.length?a.attributes:c.attributes;if(c.hasAttributes())for(d=0;d<b.length;d++)b[d].name===k[1]&&c.getAttribute(b[d].name)!==a.getAttribute(b[d].name)&&(null===c.getAttribute(b[d].name)?a.removeAttribute(b[d].name):a.setAttribute(b[d].name,c.getAttribute(b[d].name)));else if(a.hasAttributes())for(b=
a.attributes,d=0;d<b.length;d++)a.removeAttribute(b[d].name)},move:function(a,b,c,d){var q=function(a,b){for(var c=a.children.length-1;0<=c;c--)if(a.children[c].isEqualNode(b))return c;return-1};c=q(d,c);q=q(b,a);c===d.children.length-1?b.appendChild(a):(c>q&&c++,b.insertBefore(a,b.children[c]))},nodeAbove:n,nodeBelow:p,nodeWithin:r,imageBannerAbove:n,imageBannerBelow:p,imageBannerWithin:r,remove:function(a,b,c,d){for(var q=d.children.length-1;0<=q;q--)if(d.children[q].isEqualNode(c)){b.insertBefore(a,
b.children[q]);break}},link:function(b,c,d,k,f){"a"===b.nodeName.toLowerCase()?u.rollbackHandlers.attribute(b,c,d,k,[f[0],"href"]):a(b)&&a(b.parentNode)&&b.parentNode.parentNode.replaceChild(b,b.parentNode)},changeImageBanner:function(a,b,c,d,k){var q=a.nodeName.toLowerCase(),f=[];k[1].imageUrl&&f.push("src");k[1].imageAlt&&f.push("alt");k[1].imageTitle&&f.push("title");if("img"===q)u.rollbackAttributes(a,c,f),"a"===b.nodeName.toLowerCase()&&k[1].linkUrl&&u.rollbackAttributes(b,d,["href"]);else if("a"===
q.toLowerCase())for(void 0!==k[1].linkUrl&&u.rollbackAttributes(a,c,["href"]),a=a.children,c=c.children,b=0;b<a.length;b++)for(d=0;d<c.length;d++)a[b].isEqualNode(c[d])&&"img"===a[b].nodeName.toLowerCase()&&u.rollbackAttributes(a[b],c[d],f)},changeLinkUrl:function(a,b,c){null===c.getAttribute("href")?a.removeAttribute("href"):a.setAttribute("href",c.getAttribute("href"))},trackClicks:function(a,b,c,d,k){return g("DomPlain").removeTrackClicks(a,k[1])}};this.isChangedHandlers={style:function(a,b,c,
d,k,f,e){for(a=0;a<=m.length-1;a++)if(m[a].method===k&&m[a].node.isEqualNode(c)&&u.isEqualToolArguments(e,m[a].args))return m[a];return!1},html:function(a,b,c){return a.innerHTML===c.innerHTML},attribute:function(a,b,c){if(c.isEqualNode(a)){for(var d=0;d<c.attributes.length;d++)if(b=a.attributes[d].nodeName,c.getAttribute(b)!==a.getAttribute(b))return!1;return!0}return!1},move:function(a,b,c,d,k,f){for(a=0;a<=m.length-1;a++)if(m[a].method===k&&m[a].parent.isEqualNode(d)&&u.isEqualToolArguments(f,
m[a].args)){for(c=b=0;c<=d.children.length-1;c++){if(!m[a].parent.children[c]||!d.children[c].isEqualNode(m[a].parent.children[c])){b=0;break}b++}if(b===d.children.length)return m[a]}return!1},nodeAbove:z,nodeBelow:z,nodeWithin:function(a,b,d,k,f,e,g){for(a=0;a<=m.length-1;a++)if(h(m[a],d,f,g)&&-1<c(m[a],e).node.innerHTML.indexOf(e[1]))return m[a];return!1},imageBannerAbove:function(a,b,k,f,h,g){for(a=0;a<=m.length-1;a++)if(d(m[a],f,h,g)&&(b=c(m[a],g),f.nodeName.toLowerCase()===b.parent.nodeName.toLowerCase()&&
v(b.node.previousElementSibling,g[1])))return m[a];return e(g[1].imageUrl,g[0])?!0:!1},imageBannerBelow:function(a,b,k,f,h,g){for(a=0;a<=m.length-1;a++)if(d(m[a],f,h,g)&&(b=c(m[a],g),f.nodeName.toLowerCase()===b.parent.nodeName.toLowerCase()&&v(b.node.nextElementSibling,g[1])))return m[a];return e(g[1].imageUrl,g[0])?!0:!1},imageBannerWithin:function(a,b,d,k,f,e,g){for(a=0;a<=m.length-1;a++)if(h(m[a],d,f,g)&&(b=c(m[a],e),k.nodeName.toLowerCase()===b.parent.nodeName.toLowerCase()&&v(b.node,e[1])))return m[a];
return!1},remove:function(a,b,c,d,k,f){for(c=0;c<=m.length-1;c++)if(m[c].method===k&&m[c].parent.isEqualNode(d)&&(b=m[c],a=m[c].parent.cloneNode(!0),u.rollbackHandlers[k](m[c].node.cloneNode(!0),a,b.originNode,b.originParent),b.originParent.children.length===a.children.length)){for(var e=f=0;e<=a.children.length-1;e++)a.children[e].innerHTML===b.originParent.children[e].innerHTML&&f++;if(a.children.length===f)return b}return!1},link:function(b,c,d,k){if("a"===b.nodeName.toLowerCase())return b.getAttribute("href")===
d.getAttribute("href");if(a(k))return c.getAttribute("href")===k.getAttribute("href")},changeLinkUrl:function(a,b,c){return a.getAttribute("href")===c.getAttribute("href")},changeImageBanner:function(a,b,c,d){return"img"===a.nodeName.toLowerCase()?u.isChangedHandlers.attribute(b,b,d):u.isChangedHandlers.attribute(a,b,c)},trackClicks:function(a,b,c,d,k,f){return g("DomPlain").hasTrackClicks(c,f[1])}};this.isEqualToolArguments=function(a,b){var c=0,d=!0,k=D(a),f=D(b);if(k.length!==f.length)return!1;
var e=typeof a[0],q=typeof b[0];e!==q&&(c=1,d=!1,"string"===e&&(d=L.isNodeBelongsSelector(a[0],b[0])),"string"===q&&(d=L.isNodeBelongsSelector(b[0],a[0])));for(c;c<k.length;c++)if("object"===typeof k[c]&&!(a[c]instanceof Element)){if(JSON.stringify(k[c])!==JSON.stringify(f[c]))return!1}else if(k[c]!==f[c])return!1;return d};this.applyChangeToNode=function(a,b,c,d){d=D(d);var k=b.parentNode?b.parentNode:c;for(c=0;c<=k.children.length-1;c++)if(k.children[c].isEqualNode(b)){var f=k.children[c];break}d[0]=
f;a.apply(null,d);k=f.parentNode;return{node:f,parent:k,args:d}};this.isChanged=function(a,c,d,k){var e=1,q=d[0],h=q.parentNode?d[0].parentNode:null,g=A[a];var l=f(g)||b(g)||-1<K(g,"remove")?{node:{},parent:{},args:d}:this.applyChangeToNode(c,q.cloneNode(!0),h.cloneNode(!0),d);for(c=0;c<g.length;c++){var m=this.isChangedHandlers[g[c]].apply(u,[l.node,l.parent,q,h,a,l.args,d]);e="object"===typeof m?e&m.options.mutationIndex!==k:e&m}return 1===e};this.isActualChange=function(c){var d=k.checkConditions(c.conditions),
e=L.isNodeBelongsSelector(c.selector,c.node),q=a(c.node),h=a(c.parent);return-1<K(c.type,"remove")?(c=L.find(c.selector),d&&h&&0===c.length):f(c.type)&&-1===c.parent.innerHTML.indexOf(c.args[1])?!1:b(c.type)?v(c.parent,c.args[1])&&d&&e:d&&q&&e};this.isNeedRollback=function(a){if(-1<K(a.type,"remove")){for(var c=L.find(a.selector),d=!0,k=0;k<c.length;k++)if(c[k].isEqualNode(a.originNode)){d=!1;break}return d}if(f(a.type)){c=document.createElement("div");c.innerHTML=a.args[1];if(0<c.children.length)for(k=
0;k<c.children.length;k++)c.children[k].style.cssText=c.children[k].style.cssText,""===c.children[k].getAttribute("style")&&c.children[k].removeAttribute("style");if(-1===a.parent.innerHTML.indexOf(c.innerHTML)&&a.parent.children.length===a.originParent.children.length&&a.node.children.length==a.originNode.children.length)return!1}return b(a.type)&&!1===v(a.parent,a.args[1])&&a.parent.children.length===a.originParent.children.length&&a.node.children.length==a.originNode.children.length?!1:-1<K(a.type,
"attribute")?L.isNodeBelongsSelector(a.args[0],a.node)||a.node.getAttribute(a.args[1])===a.args[2]:-1<K(a.type,"changeImageBanner")?L.isNodeBelongsSelector(a.args[0],a.node)||v(a.parent,a.args[1]):!0};this.runRollback=function(a,b){if(F(a))a.apply(null,b);else if(Q(a))for(var c=0;c<a.length;c++)u.runRollback(a[c],b);else J(a)&&F(u.rollbackHandlers[a])&&u.rollbackHandlers[a].apply(this,b)};this.runRollbackAll=function(a){for(var b=m.length-1;0<=b;b--)this.isActualChange(m[b])&&!0!==a||(this.isNeedRollback(m[b])&&
u.runRollback(m[b].type,[m[b].node,m[b].parent,m[b].originNode,m[b].originParent,m[b].args,m[b].options]),m.splice(b,1))};this.makeRollbackObject=function(a,b,c,d,k){return{node:a,parent:a.parentNode,originNode:a.cloneNode(!0),originParent:a.parentNode?a.parentNode.cloneNode(!0):null,method:c,conditions:b,args:d,selector:k,type:A[c],options:{}}};this.registerRollback=function(a,b){a.options=b;m.push(a)}});a.exports=e},Watcher:function(a,e,g){a.config={singleton:!0};e=e("Class").extend(function(){var a=
window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver||null,e={attributes:!0,attributeFilter:["src","href"],childList:!0,subtree:!0,characterData:!0,attributeOldValue:!0,characterDataOldValue:!0};this.watchNode=function(g,d){if(null===a)return!1;var h=new a(function(){h.disconnect();d();h.observe(g||document,e)});h.observe(g||document,e);return!0}});a.exports=e},BaseWidget:function(a,e,g){a.config={singleton:!1};e=e("Class").extend(function(a){function e(a,b){for(;a&&
a.parentNode;)if(a=a.parentNode,a===b)return!0;return!1}function l(){function a(a){return!a||!X(a.displayedCount)||a.displayedCount>=b.showsCount?1:a.displayedCount+1}var b=p.options.showFrequency;if(!0!==b.always){var c=new Date,d=p.getWidgetData(),f=d.persistent,d=d.session,e;b.showsInterval&&"session"===b.showsInterval&&(e={lastShown:c,displayedCount:a(d)});c={lastShown:c,wasDismissed:f&&f.wasDismissed||!1,displayedCount:a(f)};p.setWidgetData(c,e)}}function d(){var a=p.getWidgetData(),b=a.persistent;
p.setWidgetData({lastShown:b&&b.lastShown,wasDismissed:!0,displayedCount:b&&b.displayedCount},a.session)}function h(){function a(){var a=f.lastShown&&f.lastShown.getTime();if(!E(h)){if("session"===h)return!d.session;if("campaign"===h)return!d.persistent;var b=new Date,k=b.getMonth(),b=b.getFullYear();if(k={hour:36E5,day:864E5,week:6048E5,month:864E5*(new Date(b,k,0)).getDate()}[h])return c-a>k}}var b=p.options.showFrequency;if(!(!0!==b.always&&b.showsInterval||b.neverAfterDismiss))return!0;var c=
new Date,d=p.getWidgetData(),f=d.persistent,e=d.session;if(f&&!0===b.neverAfterDismiss&&!0===f.wasDismissed)return!1;if(!0===b.always||!b.showsInterval)return!0;var h=G(b.showsInterval.toLowerCase()),b=b.showsCount;if(!E(h)&&b&&X(b)){if("session"===h&&!d.session||!d.persistent)return!0;var g=a();return"session"===h?e.displayedCount<b:f.displayedCount<b||g}}var c=g("CGApi"),f=g("Engine").events,b=g("Dom"),C=g("DomPlain"),z=g("QuerySelector"),p=this,n=!1,r=[],u=[];p.target=document.body;p.selectors=
{guidAttr:"data-vcb-me-guid",wrapper:"vcb-me-wrapper",overlay:"vcb-me-overlay",contentWrapper:"vcb-me-content-wrapper",content:"vcb-me-content",contentInner:"vcb-me-content-inner",dismiss:"vcb-me-dismiss",pointer:"vcb-me-pointer"};p.type="BaseWidget";p.wrapper=null;p.contentWrapper=null;p.content=null;p.setWidgetData=function(a,b){var d=p.options.guid;a&&c.setData(d+"persistData",JSON.stringify(a),365);b&&c.setData(d+"sessionData",JSON.stringify(b),0)};p.getWidgetData=function(){var a=p.options.guid,
b={persistent:void 0,session:void 0};if(!E(a)){var d=c.getData(a+"sessionData"),a=c.getData(a+"persistData");E(a)||(b.persistent=JSON.parse(a),b.persistent.lastShown=new Date(b.persistent.lastShown));E(d)||(b.session=JSON.parse(d),b.session.lastShown=new Date(b.session.lastShown))}return b};p.clearWidgetData=function(){var a=p.options.guid;E(a)||(c.clearData(a+"persistData"),c.clearData(a+"sessionData"))};p.validateOptions=function(a){var b=[];a.appearance.name||b.push("Can't create widget! Name parameter required!");
a.guid||b.push("Can't create widget! Guid parameter required!");a.content||b.push("Can't create widget! Content is required!");if(b.length)throw Error(b.join("\n"));};p.addClassesAndIdContentElements=function(){for(var a=p.getContentWrapper(),b=p.options,a=a.firstChild;null!==a&&1!==a.nodeType;)a=a.nextSibling;if(a){a.id||(a.id=b.guid);C.addClass(a,p.selectors.content);if(!E(b.closeEvent.dismissElements)){var c=z.find(b.closeEvent.dismissElements,a);for(b=0;b<c.length;b++)C.addClass(c[b],p.selectors.dismiss)}for(b=
a.lastChild;null!==b&&1!==b.nodeType;)b=b.previousSibling;!b||c&&~K(c,b)||C.addClass(b,p.selectors.contentInner)}};p.getWrapper=function(){if(e(p.wrapper,p.target))return p.wrapper;var a=z.find("["+p.selectors.guidAttr+'="'+p.options.guid+'"]',p.target)[0];if(a)return a};p.wrapperFor=function(a){return function(){if(!e(p[a],p.target)){var b=p.getWrapper();p[a]=z.find("."+p.selectors[a],b)[0]}return p[a]}};p.getContentWrapper=p.wrapperFor("contentWrapper");p.getContent=p.wrapperFor("content");p.bindWidgetShowEvents=
function(){var a=function(){h()&&p.show()},b=p.options.displayEvent,c;!0===b.onPageLoad&&f.domReady(a);if(!E(b.initAttachedTo)){var d=z.find(b.initAttachedTo);for(c=0;c<d.length;c++)!0===b.onClick&&C.addEvent(d[c],"click",a),!0===b.onMouseOver&&C.addEvent(d[c],"mouseover",a),!0===b.onMouseOut&&C.addEvent(d[c],"mouseout",a)}if(b.delay){var e=1E3*parseInt(b.delay,10);if(b.startAfterIdle){var g;C.addEvent(document,"ontouchstart"in window?"touchmove":"mousemove",function(){window.clearTimeout(g);g=window.setTimeout(a,
e)})}else window.setTimeout(a,e)}b.onLosePageFocus&&(C.addEvent(window,"blur",a),C.addEvent(window,"pagehide",a));b.onViewportMouseOut&&C.addEvent(document,"mouseout",function(a){(a=a.relatedTarget||a.toElement)&&"html"!==a.nodeName.toLowerCase()||h()&&p.show()});if(!E(b.onCustomEvent))f.on(b.onCustomEvent,a)};p.bindDismissEvents=function(){var a=p.getWrapper(),b=p.options.closeEvent;if(b.onDismissButton&&!E(b.dismissElements))for(a=z.find(b.dismissElements,a),b=0;b<a.length;b++)C.addEvent(a[b],"click",
p.dismiss)};p.bindCloseEvents=function(){function a(a){var c=z.find(p.options.displayEvent.initAttachedTo||""),d=p.getWrapper(),d=z.find("*:not(."+p.selectors.overlay+")",d);if(~K(c,a.target)||~K(d,a.target))return!1;b()}var b=p.hide;p.options.closeEvent.onClickOutside&&(C.addEvent(document,"click",a),C.addEvent(window,"keydown",function(a){27===(H(a.which)?a.keyCode:a.which)&&b()}))};p.show=function(){var a=p.getWrapper();C.show(a);for(a=0;a<r.length;a++)r[a].call(null);n=!0};p.hide=function(){var a=
p.getWrapper();b.hide(a);n=!1};p.dismiss=function(){p.hide();for(var a=0;a<u.length;a++)u[a].call(null)};p.destroy=function(){var a=p.getWrapper();a&&a.parentNode&&a.parentNode.removeChild(a)};p.getOptions=function(){return p.options};p.isShown=function(){return n};p.subscribeFunctionOnImgsLoads=function(a){for(var b=z.find("img"),c=0;c<b.length;c++)C.addEvent(b[c],"load",a)};p.init=function(){p.options=p.mergeWithDefaultWidgetOptions(a);p.validateOptions(p.options);u.push(d);r.push(l);p.createWidgetDom();
p.bindWidgetShowEvents()}});a.exports=e},Lightbox:function(a,e,g){a.config={singleton:!1};e=e("BaseWidget").extend(function(){function a(){var a=c.getOverlay(),d=c.options.appearance,f={display:"block",position:"fixed",top:"0px",left:"0px",height:"100%",width:"100%"};d.fadeEnabled?(f["background-color"]=d.fadeColor,f.opacity=parseFloat(d.opacity)):f.opacity=0;h.updateElementStyle(a,I(f))}function e(){var a=c.getContentWrapper(),d=c.options.appearance,f={};f["background-color"]=d.backgroundColor;f.position=
"fixed";d.autofit?(f.display="inline-block",f.width="auto",f.height="auto"):(f.width=d.width,f.height=d.height);h.updateElementStyle(a,I(f))}function v(){var a=c.getContentWrapper();h.updateElementStyle(a,I({top:0,left:0}));var d={},f=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,e=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight,g=parseInt(h.getStyle(a,"width"),10),l=parseInt(h.getStyle(a,"height"),10),v=(e<l?e-30:l)/2;d.position=
e<l+v-60?"absolute":"fixed";d.top="50%";d.left="50%";d["margin-top"]=-1*v+"px";d["margin-left"]=(f<g?f:g)/2*-1+"px";h.updateElementStyle(a,I(d))}var d=g("Dom"),h=g("DomPlain"),c=this,f=c.base;c.type="Lightbox";c.widgetOverlay=null;c.getOverlay=c.wrapperFor("overlay");c.mergeWithDefaultWidgetOptions=function(a){return R({appearance:{backgroundColor:"#FFFFFF",fadeEnabled:!0,fadeColor:"#000000",opacity:.8,autofit:!0},displayEvent:{},closeEvent:{onDismissButton:!0,onClickOutside:!0},showFrequency:{always:!0,
neverAfterDismiss:!0}},a)};c.show=function(){a();e();v();c.subscribeFunctionOnImgsLoads(v);f.show()};c.createWidgetDom=function(){c.wrapper=document.createElement("div");c.wrapper.setAttribute(c.selectors.guidAttr,c.options.guid);h.addClass(c.wrapper,c.selectors.wrapper);d.hide(c.wrapper);c.target.appendChild(c.wrapper);c.widgetOverlay=document.createElement("div");h.addClass(c.widgetOverlay,c.selectors.overlay);c.wrapper.appendChild(c.widgetOverlay);a();d.bringToFront(c.widgetOverlay);c.contentWrapper=
document.createElement("div");h.addClass(c.contentWrapper,c.selectors.contentWrapper);c.wrapper.appendChild(c.contentWrapper);c.contentWrapper.innerHTML=c.options.content;c.addClassesAndIdContentElements();e();d.bringToFront(c.contentWrapper);c.bindCloseEvents();c.bindDismissEvents()};c.init()});a.exports=e},Notification:function(a,e,g){a.config={singleton:!1};e=e("BaseWidget").extend(function(){var a=g("Dom"),e=g("DomPlain"),v=g("QuerySelector"),d=this,h=d.base;d.type="Notification";d.mergeWithDefaultWidgetOptions=
function(a){return R({appearance:{backgroundColor:"#FFFFFF"},displayEvent:{},closeEvent:{onDismissButton:!0},showFrequency:{always:!0}},a)};d.createWidgetDom=function(){d.wrapper=document.createElement("div");d.wrapper.setAttribute(d.selectors.guidAttr,d.options.guid);e.addClass(d.wrapper,d.selectors.wrapper);a.hide(d.wrapper);d.target.appendChild(d.wrapper);d.contentWrapper=document.createElement("div");e.addClass(d.contentWrapper,d.selectors.contentWrapper);d.contentWrapper.innerHTML=d.options.content;
d.wrapper.appendChild(d.contentWrapper);d.addClassesAndIdContentElements();d.bindCloseEvents();d.bindDismissEvents()};d.show=function(){var a=d.getWrapper(),f,b=d.options.appearance;if(!E(b.insertWithin))(f=v.find(b.insertWithin)[0])&&f.appendChild(a);else if(!E(b.insertAbove))(f=v.find(b.insertAbove)[0])&&f.parentElement.insertBefore(a,f);else if(!E(b.insertBelow))(f=v.find(b.insertBelow)[0])&&f.parentElement.insertBefore(a,f.nextSibling);else if(!E(b.insertWithReplace)&&(f=v.find(b.insertWithReplace)[0])){for(;f.hasChildNodes();)f.removeChild(f.firstChild);
f.appendChild(a)}if(f){a=d.getContentWrapper();f=d.getContent();var b=d.options.appearance,g={},l={};l["background-color"]=b.backgroundColor;b.autofit?(g.display="inline-block",g.width="auto",g.height="auto"):(g.width=b.width,g.height=b.height,g["margin-left"]="auto",g["margin-right"]="auto",l.width="100%",l.height="100%");e.updateElementStyle(f,I(l));e.updateElementStyle(a,I(g));h.show()}};d.hide=function(){var a=d.getWrapper();d.target.appendChild(a);h.hide()};d.init()});a.exports=e},Callout:function(a,
e,g){a.config={singleton:!1};e=e("BaseWidget").extend(function(){function a(a){return"top"===a}function e(a){return"bottom"===a}function v(a){return"left"===a}function d(a){return"right"===a}function h(a){return"center"===a}function c(a){a=a.getBoundingClientRect();var b=H(window.pageXOffset)?document.documentElement.scrollLeft:window.pageXOffset,c=H(window.pageYOffset)?document.documentElement.scrollTop:window.pageYOffset,d=a.top+c,f=a.left+b,c=a.bottom+c,b=a.right+b;return{top:d,left:f,bottom:c,
right:b,width:a.width||b-f,height:a.height||c-d}}function f(a){var b=(a||"").split(" ");a=G(b[0]||"left").toLowerCase();b=G(b[1]||"top").toLowerCase();return{side:a,part:b}}function b(a){var b=(a||"").split(" ");a=parseInt(b[0]||0,10);b=parseInt(b[1]||0,10);return{side:a,part:b}}function C(k,g,l,p){function q(){v(r.part)?n.left=x.part:h(r.part)?n.left=t.width/2-P/2+x.part:d(r.part)&&(n.left=t.width-P-x.part)}function m(){a(r.part)?n.top=x.part:h(r.part)?n.top=t.height/2-M/2+x.part:e(r.part)&&(n.top=
t.height-M-x.part)}var n={},r=f(l),x=b(p),t={};if("page"===g||"viewport"===g)t.top=t.right=t.bottom=t.left=0,"page"===g?(l=c(document.body),t.width=l.width,t.height=l.height):(t.width=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,t.height=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight);if(k=w.find(k)[0]){k=c(k);var P=k.width,M=k.height;v(r.side)?(m(),n.left=x.side):d(r.side)?(m(),n.left=t.width-P-x.side):e(r.side)?(q(),n.top=
t.height-M-x.side):a(r.side)?(q(),n.top=x.side):h(r.side)&&h(r.part)&&(n.left=t.width/2-P/2+x.side,n.top=t.height/2-M/2+x.part);n.position="viewport"===g?"fixed":"absolute";return n}}function z(k,g,l,p){function q(){a(r.part)?n.top=t.top-x.part:h(r.part)?n.top=t.top+t.height/2-M/2+x.part:e(r.part)&&(n.top=t.bottom-M+x.part)}function m(){v(r.part)?n.left=t.left-x.part:h(r.part)?n.left=t.left+t.width/2-P/2+x.part:d(r.part)&&(n.left=t.right-P+x.part)}var n={},r=f(l),x=b(p),t={};if(g){g=w.find(g)[0];
if(!g)return;t=c(g)}if(k=w.find(k)[0]){g=c(k);var P=g.width,M=g.height;k=k.offsetParent||document.body;g=u.getStyle(k,"position");if("relative"===g||"absolute"===g||"fixed"===g)k=c(k),t.top-=k.top,t.left-=k.left,t.right=t.left+t.width,t.bottom=t.top+t.height;v(r.side)?(q(),n.left=t.left-P-x.side):d(r.side)?(q(),n.left=t.right+x.side):a(r.side)?(m(),n.top=t.top-M-x.side):e(r.side)?(m(),n.top=t.bottom+x.side):h(r.side)&&h(r.part)&&(n.left=t.left+t.width/2-P/2+x.part,n.top=t.top+t.height/2-M/2+x.part);
n.position="absolute";return n}}function p(){function b(a,b){b=b||"px";var c=["z-index"],d={},f;for(f in a)if(a.hasOwnProperty(f)){var e=a[f];X(e)&&0!==e&&!~K(c,f)&&(e+=b);d[f]=e}return d}function g(a,b){u.updateElementStyle(a,I(b));u.updateElementStyle(a.children[0],I({width:0,height:0}))}function l(b,k,g,l){function p(c){var f,k="side"===c?"part":"side";a(x[c])||e(x[c])?f=r.top-t.height<q&&r.bottom+t.height<m.height+q&&r.bottom+t.height>q?"bottom":r.top+t.height>m.height+q&&r.top-t.height>q&&r.top-
t.height<m.height+q?"top":x[c]:d(x[c])||v(x[c])?f=r.right+t.width>m.width+n&&r.left-t.width>n&&r.left-t.width<m.width+n?"left":r.left-t.width<n&&r.right+t.width<m.width+n&&r.right+t.width>n?"right":x[c]:h(x[c])&&(f=a(x[k])||e(x[k])?0>b.left?"right":b.left+t.width>m.width?"left":x[c]:v(x[k])||d(x[k])?0>b.top?"top":b.top+t.height>m.height?"bottom":x[c]:x[c]);return f}var m={width:window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,height:window.innerHeight||document.documentElement.clientHeight||
document.body.clientHeight},n=H(window.pageXOffset)?document.documentElement.scrollLeft:window.pageXOffset,q=H(window.pageYOffset)?document.documentElement.scrollTop:window.pageYOffset,t=R({},c(g));g=w.find(l)[0];var r=c(g),x=f(k);b=R({},b);b.top-=q;b.left-=n;t.top-=q;t.left-=n;t.bottom-=q;t.right-=n;k=p("side");g=p("part");return k+" "+g}var p=k.getContentWrapper(),n=k.options.appearance,m=k.options.appearance.position,A=m.at;var y={};u.updateElementStyle(p,I({top:0,left:0}));if("page"===m.relativeTo||
"viewport"===m.relativeTo)y=C(p,m.relativeTo,A,m.offset),y=b(y);else if(!E(m.relativeTo)){y=z(p,m.relativeTo,A,m.offset);if(m.viewportDetection){var x=l(y,A,p,m.relativeTo);x!==A&&(A=x,y=z(p,m.relativeTo,A,m.offset))}y=b(y)}u.updateElementStyle(p,I(y));(function(h,l,m){function q(a,b){var c=a;b&&2*a>b&&(c=b-a,c=0>c?0:c);return c}var t=k.getContent(),x=k.getPointer(),P=x&&x.children[0],C=!1,y=1,A=1,N=0,M=0,B="0 ",D={},H={width:0,height:0,"border-top":"none","border-bottom":"none","border-left":"none",
"border-right":"none"};if(l){var F=f(h),L=c(p);var G=F.part;"page"===m||"viewport"===m?(J(l)?(m=f(l),h=m.side,G=m.part,C=h!==F.side&&h!==F.part):(h=F.side,l=h+" "+G),A=-1):(h={top:"bottom",bottom:"top",left:"right",right:"left"}[F.side],l=h+" "+G,y=-1,m=w.find(m)[0],D=c(m));var E=function(b){b=a(b)||e(b)?"width":v(b)||d(b)?"height":void 0;b=Math.ceil(3*Math.log(L[b]));return 7>b?7:b}(h);m=function(a){var b=E+"px solid "+n.backgroundColor,c=E+"px solid transparent";return R(H,{top:{"border-bottom":b,
"border-left":c,"border-right":c},bottom:{"border-top":b,"border-left":c,"border-right":c},right:{"border-top":c,"border-bottom":c,"border-left":b},left:{"border-top":c,"border-bottom":c,"border-right":b}}[a])}(h);u.updateElementStyle(x,I(m));m=c(x);F=a(G)||e(G)?q(m.height,D.height):0;D=v(G)||d(G)?q(m.width,D.width):0;a(h)?(M=m.height,B+=-D):e(h)?(M=m.height*A*y,B+=-D):v(h)?(N=m.width,B+=-F):d(h)&&(N=m.width*A*y,B+=-F);C||r.freeMove(p,N,M);l=b(z(x,t,l,B));u.updateElementStyle(x,I(l));P&&(x=P.children[0],
l=Math.sqrt(2*Math.pow(E,2)),t={margin:0,padding:0,"box-shadow":u.getStyle(t,"box-shadow"),transform:"rotate(45deg)",position:"absolute","z-index":-1,width:l,height:l},y={position:"absolute",overflow:"hidden",top:-E,left:-E,width:2*m.width,height:2*m.height},N=E-l/2+m.width/2,M=-E-m.width/2,B=E-l/2+m.height/2,m=-E-m.height/2,a(h)?(t.top=2*E-l/2,t.left=N,y.left=M):e(h)?(t.top=-l/2,t.left=N,y.left=M):v(h)?(t.top=B,t.left=2*E-l/2,y.top=m):d(h)&&(t.top=B,t.left=-l/2,y.top=m),u.updateElementStyle(P,I(b(y))),
u.updateElementStyle(x,I(b(t))))}else g(x,H)})(A,m.pointer,m.relativeTo)}function n(){m.isShown()&&p()}var r=g("Dom"),u=g("DomPlain"),w=g("QuerySelector"),k=this,m=k.base;k.type="Callout";k.pointer=null;var A;k.updatePositionEventHandler=function(){A&&clearTimeout(A);A=setTimeout(n,100)};k.mergeWithDefaultWidgetOptions=function(a){return R({appearance:{backgroundColor:"#FFFFFF",autofit:!0,position:{at:"top left",relativeTo:"viewport"}},displayEvent:{},closeEvent:{onDismissButton:!0},showFrequency:{always:!0}},
a)};k.getPointer=k.wrapperFor("pointer");k.createWidgetDom=function(){k.wrapper=document.createElement("div");k.wrapper.setAttribute(k.selectors.guidAttr,k.options.guid);u.addClass(k.wrapper,k.selectors.wrapper);r.hide(k.wrapper);k.target.appendChild(k.wrapper);k.contentWrapper=document.createElement("div");u.addClass(k.contentWrapper,k.selectors.contentWrapper);k.contentWrapper.innerHTML=k.options.content;k.wrapper.appendChild(k.contentWrapper);r.bringToFront(k.contentWrapper);k.addClassesAndIdContentElements();
k.pointer=document.createElement("span");u.addClass(k.pointer,k.selectors.pointer);u.updateElementStyle(k.pointer,I({width:0,height:0,margin:0,padding:0,display:"inline-block"}));k.contentWrapper.appendChild(k.pointer);var a=document.createElement("div");k.pointerShadow=document.createElement("div");k.pointerShadow.appendChild(a);k.pointer.appendChild(k.pointerShadow);k.bindCloseEvents();k.bindDismissEvents()};k.show=function(){var a=k.getContentWrapper(),b=k.getContent(),c=k.options.appearance,d=
{},f={};f["background-color"]=c.backgroundColor;c.autofit?(d.display="inline-block",d.width="auto",d.height="auto"):(d.width=c.width,d.height=c.height,f.width="100%",f.height="100%");f=R(d,f);u.updateElementStyle(b,I(f));u.updateElementStyle(a,I(d));p();window.addEventListener("resize",k.updatePositionEventHandler);window.addEventListener("scroll",k.updatePositionEventHandler);k.subscribeFunctionOnImgsLoads(p);m.show()};k.init=function(){m.init()};k.init()});a.exports=e},Widgets:function(a,e,g){a.config=
{singleton:!0};e=e("Class").extend(function(){var a=this;this.createLightbox=function(a,e){a.guid=e;g("Lightbox",a)};this.createNotification=function(a,e){a.guid=e;g("Notification",a)};this.createCallout=function(a,e){a.guid=e;g("Callout",a)};this.getWrapper=function(){return B(a,"createLightbox","createCallout","createNotification")}});a.exports=e},Dlp:function(a,e,g){a.config={singleton:!0};var l=e("Class").extend(function(a){function l(a){if(a.origin===r){a=a.data;try{var b=JSON.parse(a)}catch(A){w.log("Can not parse message,\nbecause of: "+
A.message+"\nerror with object:",a)}if(b)if(b.request)try{b.command&&y[b.command](b)}catch(A){w.log('Can not execute "'+b.command+'" request command,\nbecause error occurred: '+A.message)}else if(b.error&&w.log(b.error),a=p[b.hash]){try{b.error?a.reject({error:b.error,data:b.data}):a.resolve(b.data)}catch(A){w.log(A)}delete p[b.hash]}}}function d(a,b){return{hash:Y(),command:a,data:b}}function h(a){try{window.parent.postMessage(JSON.stringify(a),r)}catch(A){w.log("Can not send event through post message,\nbecause of: "+
A.message+"\nerror with object:",a);var b=p[a.hash];b&&(b.reject({error:A,data:void 0}),delete p[a.hash])}}function c(a){var b=new C;p[a.hash]=b;h(a);return b.promise()}function f(a,b,c){return function(){for(var f={},e=0;e<c.length;e++)f[c[e]]=arguments[e];return a(d(b,f))}}var b=this,C=e("Deferred"),z=g("Action"),p={},n=new C,r=a.dlpOrigin,u={},y={console:function(a){a=a.data;w[a.method](a.message)},raiseEvent:function(a){u[a.data.handlerHash]()},"Action.sendActions":function(a){a=a.data.args;var b=
a[2];a[2]=function(){h(d("runCallback",{handler:b}))};z.sendActions.apply(z,a)}};this.parentReady=function(a){n.done(fa(a));return"resolved"===n.state()};this.proxy=function(a,b,f){return function(){var e={args:D(arguments),promised:f};return(f?c:h)(d(a+"."+b,e))}};this.trackClicks=function(a,b,c,f){h(d("Dom.trackClicks",{args:[a,b,c]}))};this.addListener=function(a,b,c){a=d("Dom.addListener",{selector:a,eventName:b});for(e in u)if(u.hasOwnProperty(e)&&u[e]===c){var f=e;break}var e=a.data;f?e.handlerHash=
f:(e.handlerHash=Y(),u[e.handlerHash]=c);h(a)};this.removeListener=function(a,b,c){a=d("Dom.removeListener",{selector:a,eventName:b});for(var f in u)if(u.hasOwnProperty(f)&&u[f]===c){a.data.handlerHash=f;h(a);break}};this.checkNodeExist=f(c,"checkNodeExist",["selector"]);this.navigateTo=f(h,"navigateTo",["url"]);addEventListener?addEventListener("message",l,!1):attachEvent("onmessage",l);n=c(d("parentReady"));this.isDlpEnabled=function(){return!0};this.getWrapper=function(){return B(b,"isDlpEnabled")}});
a.basic=function(){var a=this;this.getWrapper=function(){return B(a,"isDlpEnabled")};this.isDlpEnabled=function(){return!1}};a.dlp=l},Modules:function(a,e,g){var l=e("Class");g=l.extend(function(){var a=this,g={cgapi:{},campaign:{alias:"Campaign",args:["campaignData"]},site:{alias:"Site"},renderer:{alias:"Renderer",args:["campaign"]},element:{},html:{},css:{},Deferred:{},when:{},events:{alias:"Events"},actions:{alias:"Action"},visitor:{alias:"Visitor"},modules:{alias:"Modules"},dom:{alias:"Dom"},
cookies:{alias:"Cookies"},style:{alias:"Style"},recommendations:{}},d=[],h=[],c={};this.define=function(a,b,c){if(!a||"string"!==typeof a)return w.log("Invalid module alias ( "+a+" )."),this;if(d[a])return d[a].reserved?w.log("Reserved name can not be used ( "+a+" )."):w.log("Module with this alias already defined  ( "+a+" )."),this;"function"===typeof b?(c=b,b={}):"string"===typeof b?b={extend:b}:b&&"object"===typeof b||(b={});"undefined"===typeof b.singleton&&(b.singleton=!0);"undefined"===typeof b.autoDefine&&
(b.autoDefine=!0);if("undefined"!==typeof b.extend&&("string"!==typeof b.extend||!b.extend))return w.log("Invalid parent alias ( "+b.extend+" )"),this;if(b.extend&&(!d[b.extend]||d[b.extend].reserved&&!d[b.extend].standard))return w.log("Parent module is not defined ( "+b.extend+" )"),this;if(!c||"function"!==typeof c)return w.log("Invalid module function ( "+a+" )."),this;if(b.extend){var f=d[b.extend];if(f.reserved&&f.standard){var g=e(f.standard);"undefined"===typeof g.extend&&(g=l.extend(g));
var n=f.args}else g=f.func;c=g.extend(c)}else c=l.extend(c);d[a]={func:c,extend:b.extend,extendArgs:n,reserved:!1,singleton:b.singleton,autoDefine:b.autoDefine};!0===b.autoDefine&&h.push(a);return this};this.require=function(a){if(a&&"string"===typeof a){var b=d[a];if(b&&!0!==b.reserved){a=b.instance;if(!a||!b.singleton)if(b.extendArgs){var f=[];for(h in b.extendArgs)b.extendArgs.hasOwnProperty(h)&&f.push(c[b.extendArgs[h]]);var e=function(){e.prototype=b.func.prototype;return b.func.apply(this,f)};
a=new e}else a=new b.func;if(b.singleton){b.instance=a;var h={};var g=a,l;for(l in g)g.hasOwnProperty(l)&&(h[l]="function"===typeof g[l]?function(a){return function(){return g[a].apply(g,arguments)}}(l):g[l]);a=h}return a}w.log("Module is not registered ( "+a+" ).")}else w.log("Invalid module alias ( "+a+" ).")};this.getWrapper=function(d){d&&(c=d);return B(a,"define","require")};this.mergeInstances=function(c){c=c||{};for(var b in h)if(h.hasOwnProperty(b)){var d=h[b];c[d]||(c[d]=a.require(d))}return c};
(function(){for(var a in g)if(g.hasOwnProperty(a)){var b=g[a];d[a]=b&&b.alias?{reserved:!0,standard:b.alias,args:b.args}:{reserved:!0}}}).call(a)});a.exports=g},Vcb:function(a,e,g){a.config={singleton:!0};e=e("Class").extend(function(a){var e=this;a=(a=a.vcbParams)||{isVcbActive:!1,maxZindex:12E5,registerLoop:function(){},useZindex:function(){return!0},registerClickAction:function(){return null}};O(a,function(a,d){e[d]=a})});a.exports=e},Recommendations:function(a,e,g){a.config={singleton:!1};var l=
e("Class").extend(function(a){var l=this,d=g("CGApi"),h=e("Deferred");this.setCategoryFilter=function(a,f,b){d.setCategoryFilter(a,f,b);return this};this.setProductFilter=function(a,f,b){d.setProductFilter(a,f,b);return this};this.requestPage=function(a){var c=h();d.request({pageId:a},function(a){a?c.resolve():c.reject()});return c.promise()};this.getProducts=function(){return T(a)};this.get=function(c,f){f&&d.setProduct(f);var b=h();d.request({pageId:c},function(c){c?b.resolve(T(a)):b.reject()});
return b.promise()};this.getWrapper=function(){return B(l,"setCategoryFilter","setProductFilter","requestPage","getProducts","get")}});a.exports=l}};mmInitCallback(function(a,e,g){new function(a,e,g,d){function h(a,b,d){d=d.replace(/[^a-z0-9_]*/gi,"");b=I.mergeInstances(b);if(F(a)){var e=[];var f=a.toString();f=f.substr(f.indexOf("(")+1,f.indexOf(")")-f.indexOf("(")-1).split(",");for(var g,h=0;h<f.length;h+=1)g=G(f[h]),b.hasOwnProperty(g)?e.push(b[g]):(w.warn("CD API: Module not found "+g+" Try to update CD API version."),
e.push(void 0));try{a.apply({},e)}catch(S){S.message="Error in "+d+": "+S.message,w.error(S)}}else c(a,b,d)}function c(a,b,c){function f(a){a.apply({},g)}var e=[],g=[];F(d.scriptArgumentsWrapper)&&(b=d.scriptArgumentsWrapper(b));for(var h in b)b.hasOwnProperty(h)&&(e.push(h),g.push(b[h]));a="function "+c+"(){function inner_"+c+"("+e.join(",")+"){"+a+"\n} try {\n applier(inner_"+c+");\n} catch (e) {\ne.message = 'Error in '+scriptName+': ' + e.message;\nconsole.error(e);\n};};\n"+c+"();//# sourceURL="+
c+".js";try{ia.apply({},[a,c,f])}catch(S){S.message="Error in "+c+": "+S.message,w.error(S)}}function f(a){return"1.21"===a.HighLevelApiVersion}function b(a){a=A.require("Renderer",a);a.constructor=void 0;return a}function l(a){var c=r();c.modules=I.getWrapper(a);c.campaign=a.campaign.getContext();c.renderer=b(a.campaign);return c}function v(a){if(a=E[a])return a=l({campaign:a}),a=I.mergeInstances(a)}function p(){var a=n();return a=I.mergeInstances(a)}function n(){var a=r();a.modules=I.getWrapper({});
return a}function r(){return{site:J.getContext(),Deferred:A.requireClass("Deferred"),when:A.requireClass("When"),events:y.events.getWrapper(),actions:A.require("Action").getWrapper(),visitor:A.require("Visitor").getWrapper(),dom:A.require("Dom").getWrapper(),widgets:A.require("Widgets").getWrapper(),dlp:A.require("Dlp").getWrapper(),cookies:A.require("Cookies").getWrapper(),spa:A.require("Spa").getWrapper(),recommendations:A.require("Recommendations",O).getWrapper()}}function u(b){K||(J=A.require("Site"),
I=A.require("Modules"),K=!0);if(!d.skipPersistentData)for(var c=b.PersistData||[],e=c.length;e--;)a.setParam(c[e].Name,c[e].Value,a.baseStorage.storeStrategy.persistent,c[e].Expiration);var e,c=[],g=V(b.Campaigns||[],f),k=V(b.Scripts||[],f),q=A.requireClass("Campaign");for(e=0;e<k.length;e++)c.push({script:k[e]});for(e=0;e<g.length;e++){k=g[e].Name;E[k]?E[k].updateData(g[e]):E[k]=new q(g[e]);O[k]=E[k].getRecommendations();for(var r=0;r<g[e].Scripts.length;r++)c.push({script:g[e].Scripts[r],campaign:E[k],
campaignData:g[e]})}J.setPageExperiences(b.GenInfo||{});m=b.ServerAttributes;c.sort(function(a,b){return a.script.Order-b.script.Order});for(e=0;e<c.length;e++)b=c[e].script.Data,g=c[e].script.Name,(q=c[e].campaign)?(k=c[e].campaignData,h(b,l(c[e],{campaignData:k,campaign:q}),k.Name+"_"+g)):h(b,n(),"Site_"+g);d.debug&&(d.debug["1.21"]={context:{getSiteScriptArguments:p,getCampaignScriptArguments:v}})}d=d||{};var y=this,k=[1,0];if(a.version.split(".")[0]!=k[0]||a.version.split(".")[1]<k[1])w.log("Loader have non compatible version with High level API.");
else{var m={},k=function(){var a=location.search;if(window.parent!==window.self&&-1!==a.indexOf("original-url")&&(a=a.replace(/^\?/,"").split("&"),a=W(a,function(a){return 0===a.indexOf("original-url")}))){try{var b=decodeURIComponent(a).split("=").slice(1).join("=");var c=/http(s)?:\/\/.*?([^/]|$)+/.exec(b)[0]}catch(M){return}return c}}(),A=new ha({Engine:y},g,{isDlpEnabled:!H(k),dlpOrigin:k,vcbParams:d.vcbParams,cookieDomain:a.calcCookieDomain||a.cookie_domain||window.location.hostname.replace(/^www\./i,
""),isBaseStorageSecure:a.baseStorage.isSecure,moduleExtensions:d.moduleExtensions});A.addModule("BaseStorage",function(b){b.config={singleton:!1};b.exports=function(b){return a.baseStorage(b.namespace)}});A.addModule("Engine",function(a){a.config={singleton:!0}});var q=A.require("BaseStorage",{namespace:"mmengine"}),B={persistent:0,deferredRequest:1,request:2,page:3};this.storeStrategy=B;var D=[];D[B.page]={};D[B.request]={};var E={},J,I,K,O={};this.setParam=function(b,c,e,f){if(d.useLoaderStorage)a.setParam(b,
c,e,f);else switch(e){case B.persistent:case B.deferredRequest:a.setParam(b,c,e);break;case B.request:case B.page:D[e][b]=c;break;default:w.log("Unknown store strategy: "+e)}};this.getParam=function(b,c){if(d.useLoaderStorage)return a.getParam(b,c);switch(c){case B.persistent:case B.deferredRequest:return a.getParam(b,c);case B.request:case B.page:return D[c][b];default:w.log("Unknown store strategy: "+c)}};this.setData=function(a,b,c){q.set(a,b,c)};this.getData=function(a){return q.get(a)};this.clearData=
function(a){q.set(a,null,-1)};this.getServerAttrs=function(){return m};this.CGRequest=function(b){if(!d.useLoaderStorage){var c=a.mergeParams(D[B.page],D[B.request]);D[B.request]={}}a.CGRequest(function(a){F(b)&&b(a)},c)};this.runElementScript=function(a,c,d,e){c=a.getElement(c);var f=r();f.modules=I.getWrapper();f.campaign=a.getContext();f.renderer=b(a);f.element=c.clone();f.html=d.html;f.css=d.css;f.recommendations=A.require("Recommendations",O).getWrapper();h(e,f,a.getName()+"_"+c.Name+"_"+c.VariantName)};
this.events=A.require("EventsSite");d.skipResponseProcessing||u(e);a.on("response",u)}}(a,e,ka,g)})})()})();
